name: Benchmark

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install cargo-binstall
        uses: taiki-e/install-action@cargo-binstall

      - name: Install Hyperfine
        run: cargo binstall -y hyperfine

      - name: Install Zig
        uses: goto-bus-stop/setup-zig@v2

      - name: Run benchmarks
        shell: bash
        run: ./bench.sh
